"C:\Program Files\alchemy\alchemy.exe" "initial.bmp" -g -o -+ -Yd500
"C:\Program Files\alchemy\alchemy.exe" "it1.bmp" -g -o -+ -Yd500
"C:\Program Files\alchemy\alchemy.exe" "it2.bmp" -g -o -+ -Yd500
"C:\Program Files\alchemy\alchemy.exe" "it3.bmp" -g -o -+ -Yd500
"C:\Program Files\alchemy\alchemy.exe" "it4.bmp" -g -o -+ -Yd500
"C:\Program Files\alchemy\alchemy.exe" "it5.bmp" -g -o -+ -Yd500
"C:\Program Files\alchemy\alchemy.exe" "it6.bmp" -g -o -+ -Yd500
"C:\Program Files\alchemy\alchemy.exe" "it7.bmp" -g -o -+ -Yd500
"C:\Program Files\alchemy\alchemy.exe" "it8.bmp" -g -o -+ -Yd500
"C:\Program Files\alchemy\alchemy.exe" "it9.bmp" -g -o -+ -Yd500
"C:\Program Files\alchemy\alchemy.exe" "it10.bmp" -g -o -+ -Yd500
"C:\Program Files\alchemy\alchemy.exe" "it11.bmp" -g -o -+ -Yd500
"C:\Program Files\alchemy\alchemy.exe" "it12.bmp" -g -o -+ -Yd500
"C:\Program Files\alchemy\alchemy.exe" "it13.bmp" -g -o -+ -Yd500
"C:\Program Files\alchemy\alchemy.exe" "it14.bmp" -g -o -+ -Yd500
"C:\Program Files\alchemy\alchemy.exe" "it15.bmp" -g -o -+ -Yd500
"C:\Program Files\alchemy\alchemy.exe" "itfinal.bmp" -g -o -+ -Yd500
"C:\Program Files\alchemy\alchemy.exe" "itroots.bmp" -g -o -+ -Yd500
